FROM php:7.1-cli-alpine
MAINTAINER Kevin Bentlage <kevin@cobytes.com>

# Install basic packages
RUN apk add --update ca-certificates curl openssh-client rsync git unzip tar sudo 
 
# Install NodeJS
RUN apk add --update nodejs npm

# Install Composer
RUN curl --silent https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install WP-CLI
RUN curl --silent --output /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x /usr/local/bin/wp

# Create 'build' group and user
RUN addgroup -S build && adduser -S build -G build -h /build

# Give 'build' user sudo permissions
RUN echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Install global NPM packages
RUN npm install -g grunt yarn

# Disable SSH StrictHostKeyChecking
RUN echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config

# Switch to 'build' user
USER build
WORKDIR /build

# Prepare SSH environment
RUN mkdir -p ~/.ssh

# Configure Composer
ENV COMPOSER_NO_INTERACTION 1

# Install global Composer speedup packages
RUN composer global require hirak/prestissimo:@stable
RUN composer global require jakub-onderka/php-parallel-lint:@stable
RUN composer global require nette/code-checker:~2.5.0
