FROM php:7.0-cli-alpine
MAINTAINER Kevin Bentlage <kevin@cobytes.com>

# Install basic packages
RUN apk add --update --no-cache \
  ca-certificates \
  build-base \
  autoconf \
  sudo \
  curl rsync git \
  openssh-client \
  unzip tar \
  freetype-dev \
  libjpeg-turbo-dev \
  libpng-dev \
  libzip-dev \
  libxml2-dev

# Install bash
RUN apk add --update --no-cache bash

# Install php extensions
RUN docker-php-ext-configure gd && docker-php-ext-install gd && \
  docker-php-ext-configure zip && docker-php-ext-install zip && \
  docker-php-ext-configure bcmath && docker-php-ext-install bcmath && \
  docker-php-ext-configure soap && docker-php-ext-install soap

# Install npm
RUN apk add --update --no-cache npm

# Cleanup
RUN rm -rf /tmp/* /var/cache/apk/

# Install Composer
RUN curl --silent https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install WP-CLI
RUN curl --silent --output /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x /usr/local/bin/wp

# Create 'build' group and user
RUN addgroup -S build && adduser -S build -G build -h /build

# Give 'build' user sudo permissions
RUN echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Install global NPM packages
RUN npm install -g grunt yarn

# Disable SSH StrictHostKeyChecking
RUN echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config

# Switch to 'build' user
USER build
WORKDIR /build

# Switch to 'bash' shell
SHELL ["/bin/bash", "-c"]

# Prepare SSH environment
RUN mkdir -p ~/.ssh

# Configure Composer
ENV COMPOSER_NO_INTERACTION 1
